// state.search: byte-pattern search in the virtual state file.
//
// A full scan of a 100+ MB virtual file through the byte generator would take seconds, so the mock
// scans a *bounded, structure-aware* portion (documented in the result note):
//   - every small region (scalars, structs, arrays up to SMALL_BYTES) is scanned completely;
//   - every huge array (collections, hash tables) contributes its first quota bytes of *live* data
//     (the prefix up to its live count for collections, so empty tails are skipped);
//   - ranges are visited in ascending file offset, so the first `limit` matches in offset order are
//     returned exactly as a real scan would return them, as long as they lie inside the scanned portion.
// Every reported match is verified against the generated bytes at that offset (same generator as state.bytes).

import type { NodeLocation, SearchMatch, SearchResult } from '../contract';
import type { TNode } from './types';
import type { StateSource } from './tree';
import { locate, readRaw } from './tree';
import { contractIndexOfId, decodeIdentity } from './ids';
import { bytesToHex, hexToBytes, now, rpcError } from './util';
import type { GenSpec } from './gens';

const SMALL_BYTES = 256 * 1024;
const BUDGET_BYTES = 24 * 1024 * 1024;
const MIN_QUOTA = 2 * 1024 * 1024;
const MAX_QUOTA = 16 * 1024 * 1024;
const CHUNK = 1024 * 1024;
const TIME_CAP_MS = 4000;

export type SearchMode = 'auto' | 'id' | 'hex' | 'int' | 'text';

interface Pattern {
  mode: 'id' | 'hex' | 'int' | 'text';
  bytes: Uint8Array;
  note: string;
}

export function interpretQuery(query: string, mode: SearchMode, src: StateSource): Pattern {
  const q = query.trim();
  if (q === '') throw rpcError('invalid_params', 'Empty search query');
  let m: SearchMode = mode;
  if (m === 'auto') {
    if (/^[A-Za-z]{60}$/.test(q)) m = 'id';
    else if (/^0x[0-9a-fA-F]+$/.test(q)) m = 'hex';
    else if (/^-?\d+$/.test(q)) m = 'int';
    else if (/^[0-9a-fA-F]{2,}$/.test(q) && q.length % 2 === 0) m = 'hex';
    else m = 'text';
  }
  switch (m) {
    case 'id': {
      const d = decodeIdentity(q);
      if (!d) throw rpcError('invalid_params', 'An identity is exactly 60 letters (A-Z)');
      let note = 'Interpreted as a Qubic identity: 32 bytes as stored';
      if (!d.checksumOk) note += ' (checksum letters do not match; searched anyway)';
      const ci = contractIndexOfId(d.bytes, 0);
      if (ci > 0) note += `; this is the id of contract ${ci}${src.env.contractName(ci) ? ' (' + src.env.contractName(ci) + ')' : ''}`;
      return { mode: 'id', bytes: d.bytes, note };
    }
    case 'hex': {
      const h = q.replace(/^0x/i, '').replace(/\s+/g, '');
      const b = hexToBytes(h);
      if (!b || b.length === 0) throw rpcError('invalid_params', 'Hex patterns need an even number of hex digits');
      return { mode: 'hex', bytes: b, note: `Interpreted as ${b.length} raw byte${b.length === 1 ? '' : 's'} (hex)` };
    }
    case 'int': {
      if (!/^-?\d+$/.test(q) && !/^0x[0-9a-fA-F]+$/.test(q)) throw rpcError('invalid_params', 'Not an integer (decimal or 0x hex expected)');
      const v = BigInt(q);
      if (v < -(1n << 63n) || v >= 1n << 64n) throw rpcError('invalid_params', 'Integer does not fit in 64 bits');
      const u = BigInt.asUintN(64, v);
      const b = new Uint8Array(8);
      for (let i = 0; i < 8; i++) b[i] = Number((u >> BigInt(i * 8)) & 0xffn);
      return { mode: 'int', bytes: b, note: 'Interpreted as a 64-bit little-endian integer' };
    }
    default: {
      const b = new TextEncoder().encode(q);
      return { mode: 'text', bytes: b, note: `Interpreted as ASCII text (${b.length} byte${b.length === 1 ? '' : 's'})` };
    }
  }
}

// ---- scan plan --------------------------------------------------------------------------------------------

type Range = [number, number];

function countHuge(t: TNode, spec: GenSpec | undefined): number {
  if (t.size <= SMALL_BYTES) return 0;
  if (t.kind === 'array') return 1;
  let n = 0;
  for (const f of t.fields ?? []) n += countHuge(f.type, f.spec);
  void spec;
  return n;
}

function walk(src: StateSource, t: TNode, spec: GenSpec | undefined, off: number, quota: number, out: Range[]): void {
  if (t.size <= SMALL_BYTES) {
    out.push([off, off + t.size]);
    return;
  }
  if (t.kind === 'array') {
    const es = (t.element as TNode).size;
    let live = t.size;
    if (spec?.liveCount) live = Math.min(live, spec.liveCount(src.c) * es);
    out.push([off, off + Math.min(live, quota)]);
    return;
  }
  for (const f of t.fields ?? []) walk(src, f.type, f.spec, off + f.offset, quota, out);
}

function scanPlan(src: StateSource): Range[] {
  const root = src.def.root;
  const huge = Math.max(1, countHuge(root, undefined));
  const quota = Math.max(MIN_QUOTA, Math.min(MAX_QUOTA, Math.floor(BUDGET_BYTES / huge)));
  const raw: Range[] = [];
  walk(src, root, src.root.spec, 0, quota, raw);
  const merged: Range[] = [];
  for (const [s0, e0] of raw) {
    const s = s0;
    const e = Math.min(e0, src.fileSize);
    if (e <= s) continue;
    const last = merged[merged.length - 1];
    if (last && last[1] >= s) last[1] = Math.max(last[1], e);
    else merged.push([s, e]);
  }
  return merged;
}

// ---- scanning -------------------------------------------------------------------------------------------------

function anchorIndex(p: Uint8Array): number {
  for (let i = 0; i < p.length; i++) if (p[i] !== 0) return i;
  return 0;
}

export function runSearch(src: StateSource, query: string, mode: SearchMode, limit: number, schemaLess = false): SearchResult {
  const t0 = now();
  const pat = interpretQuery(query, mode, src);
  const p = pat.bytes;
  const plen = p.length;
  const a = anchorIndex(p);
  const av = p[a] as number;
  const offsets: number[] = [];
  const plan = scanPlan(src);
  const scanned = plan.reduce((s, r) => s + (r[1] - r[0]), 0);
  let timedOut = false;

  outer: for (const [rs, re] of plan) {
    const step = CHUNK - (plen - 1);
    for (let pos = rs; pos < re; pos += step) {
      const len = Math.min(CHUNK, re - pos);
      const last = pos + len >= re;
      const buf = readRaw(src, pos, len);
      const accept = last ? len : step;
      let from = a;
      for (;;) {
        const c = buf.indexOf(av, from);
        if (c < 0) break;
        from = c + 1;
        const start = c - a;
        if (start < 0) continue;
        if (start >= accept) break;
        if (start + plen > len) continue;
        let ok = true;
        for (let k = 0; k < plen; k++) {
          if (buf[start + k] !== p[k]) {
            ok = false;
            break;
          }
        }
        if (!ok) continue;
        offsets.push(pos + start);
        if (offsets.length > limit) break outer;
      }
      if (last) break;
      if (now() - t0 > TIME_CAP_MS) {
        timedOut = true;
        break outer;
      }
    }
  }

  const truncated = offsets.length > limit;
  const where = (o: number): NodeLocation =>
    schemaLess
      ? { id: '', path: [{ id: '', label: src.def.stateTypeName }], offset: 0, size: src.fileSize, typeName: src.def.stateTypeName }
      : locate(src, o);
  const matches: SearchMatch[] = offsets.slice(0, limit).map((o) => ({ offset: o, length: plen, location: where(o) }));
  let note = pat.note;
  if (!truncated) {
    const total = src.fileSize;
    note += scanned < total || timedOut
      ? `. Mock backend: scanned ${Math.round(scanned / 1048576)} MiB of the structure's live regions (collections / hash tables are searched from their start)`
      : '';
  }
  return {
    pattern: { mode: pat.mode, hex: bytesToHex(p), note },
    matches,
    truncated,
    elapsedMs: Math.max(0.01, Math.round((now() - t0) * 100) / 100),
  };
}
