// Build-time helper: embeds a file into a C++ source.
//   qstate-embed <input> <output.cpp> <namespace> <symbol> <is_placeholder 0|1>
//
// The generated file defines, in namespace <namespace>:
//   extern const char* const        <symbol>_chunks[];       pointers to the pieces
//   extern const unsigned long long <symbol>_chunk_sizes[];  their sizes in bytes
//   extern const unsigned long long <symbol>_chunk_count;
//   extern const unsigned long long <symbol>_size;           total size
//   extern const bool               <symbol>_placeholder;
//
// The content is split into pieces of at most 16 KiB, each one a string literal: that is far faster to compile
// than a byte array of hex numbers (8 MB: 1 s instead of 17 s) and stays below the 64 KiB string literal limit
// of MSVC. The consumer (src/assets.cpp) concatenates the pieces once at run time.
#include <cstdio>
#include <fstream>
#include <iostream>
#include <algorithm>
#include <iterator>
#include <string>
#include <vector>

namespace {

constexpr std::size_t kChunkBytes = 16 * 1024;
constexpr std::size_t kLineBytes = 100;

void writeChunk(std::ostream& out, const std::string& symbol, std::size_t index, const char* data, std::size_t size) {
    out << "static const char " << symbol << "_c" << index << "[] =\n\"";
    std::size_t column = 0;
    for (std::size_t i = 0; i < size; ++i) {
        const unsigned char c = static_cast<unsigned char>(data[i]);
        if (c == '"' || c == '\\' || c == '?') {
            out << '\\' << static_cast<char>(c);
            column += 2;
        } else if (c >= 0x20 && c < 0x7f) {
            out << static_cast<char>(c);
            column += 1;
        } else if (c == '\n') {
            out << "\\n";
            column += 2;
        } else {
            char octal[5];
            std::snprintf(octal, sizeof octal, "\\%03o", c);
            out << octal;
            column += 4;
        }
        if (column >= kLineBytes && i + 1 < size) {
            out << "\"\n\"";
            column = 0;
        }
    }
    out << "\";\n";
}

} // namespace

int main(int argc, char** argv) {
    if (argc != 6) {
        std::cerr << "usage: qstate-embed <input> <output.cpp> <namespace> <symbol> <is_placeholder>\n";
        return 2;
    }
    std::ifstream in(argv[1], std::ios::binary);
    if (!in) {
        std::cerr << "qstate-embed: cannot read " << argv[1] << "\n";
        return 1;
    }
    std::vector<char> bytes((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
    std::ofstream out(argv[2], std::ios::binary | std::ios::trunc);
    if (!out) {
        std::cerr << "qstate-embed: cannot write " << argv[2] << "\n";
        return 1;
    }
    const std::string ns = argv[3];
    const std::string sym = argv[4];
    const std::size_t chunks = bytes.empty() ? 0 : (bytes.size() + kChunkBytes - 1) / kChunkBytes;

    out << "// Generated by qstate-embed from " << argv[1] << ". Do not edit.\n"
        << "namespace " << ns << " {\n"
        << "namespace {\n";
    for (std::size_t i = 0; i < chunks; ++i) {
        const std::size_t begin = i * kChunkBytes;
        const std::size_t size = std::min(kChunkBytes, bytes.size() - begin);
        writeChunk(out, sym, i, bytes.data() + begin, size);
    }
    out << "} // namespace\n"
        << "extern const char* const " << sym << "_chunks[];\n"
        << "extern const unsigned long long " << sym << "_chunk_sizes[];\n"
        << "extern const unsigned long long " << sym << "_chunk_count;\n"
        << "extern const unsigned long long " << sym << "_size;\n"
        << "extern const bool " << sym << "_placeholder;\n"
        << "const char* const " << sym << "_chunks[] = {";
    for (std::size_t i = 0; i < chunks; ++i) {
        out << sym << "_c" << i << ",";
    }
    out << "nullptr};\n"
        << "const unsigned long long " << sym << "_chunk_sizes[] = {";
    for (std::size_t i = 0; i < chunks; ++i) {
        out << std::min(kChunkBytes, bytes.size() - i * kChunkBytes) << "ULL,";
    }
    out << "0ULL};\n"
        << "const unsigned long long " << sym << "_chunk_count = " << chunks << "ULL;\n"
        << "const unsigned long long " << sym << "_size = " << bytes.size() << "ULL;\n"
        << "const bool " << sym << "_placeholder = " << (std::string(argv[5]) == "1" ? "true" : "false") << ";\n"
        << "} // namespace " << ns << "\n";
    return out ? 0 : 1;
}
