#!/bin/bash
# Build + run the g++ ground-truth probe for research/05-contract-states-b (contracts 16..30 + test examples)
# and compare it with the Python reference layouts.
#   usage: contract_layouts_b_oracle.sh <version: v1.303.2|HEAD> <core-src-root> <work-dir>
# The probe TU is generated by contract_layouts_b.py --emit-oracle from the REAL contract_def.h contract list
# (with INCLUDE_CONTRACT_TEST_EXAMPLES) and the REAL headers; only three g++ shims are needed:
#   * oracle_shims.h : _mul128/_umul128/__shiftleft128/__shiftright128 (math_lib.h bodies) and operator""i64 (QReservePool.h)
#   * oracle_shims2.h: QPI::mod(unsigned long, unsigned long long) overload (Qdraw.h:207 deduction failure on LP64)
#   * qpi_proposals_impl_patched.h: line 971 "pv.maxVotes" -> "ProposalVotingType::maxVotes" (g++ 13 lacks P2280);
#     the change is inside a member function body and irrelevant for layout.
set -e
V="$1"; ROOT="$2"; OUT="$3"; HERE="$(cd "$(dirname "$0")" && pwd)"
mkdir -p "$OUT/overlay"
cp "$HERE/contract_layouts_b_oracle_shims.h" "$OUT/overlay/oracle_shims.h"
cp "$HERE/contract_layouts_b_oracle_shims2.h" "$OUT/overlay/oracle_shims2.h"
sed '971s/pv\.maxVotes/ProposalVotingType::maxVotes/' "$ROOT/qpi/impl/qpi_proposals_impl.h" > "$OUT/overlay/qpi_proposals_impl_patched.h"
if [ "$V" = HEAD ]; then ROOTARG="--root-head $ROOT"; else ROOTARG="--root-old $ROOT"; fi
python3 "$HERE/contract_layouts_b.py" --quiet $ROOTARG --emit-oracle "$V" "$OUT/oracle-$V.cpp"
g++ -std=c++20 -mavx2 -mbmi2 -fno-access-control -Wno-invalid-offsetof -w \
    -I "$OUT/overlay" -I "$ROOT" -I "$ROOT/.." "$OUT/oracle-$V.cpp" -o "$OUT/oracle-$V" 2> "$OUT/gcc-$V.log" \
    || { echo "COMPILE FAILED, see $OUT/gcc-$V.log"; grep -m 20 error "$OUT/gcc-$V.log"; exit 1; }
"$OUT/oracle-$V" > "$OUT/oracle-$V.out"
python3 "$HERE/contract_layouts_b.py" --quiet $ROOTARG --check-oracle "$V" "$OUT/oracle-$V.out"
